-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 23:35:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecoPlastic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecoPlastic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecoPlastic` DEFAULT CHARACTER SET utf8 ;
USE `ecoPlastic` ;

-- -----------------------------------------------------
-- Table `ecoPlastic`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`empresa` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(100) NOT NULL,
  `nombre_empresa` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `imageUrl` VARCHAR(255) NULL,
  PRIMARY KEY (`idempresa`));


-- -----------------------------------------------------
-- Table `ecoPlastic`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`roles` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `name_rol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idroles`));


-- -----------------------------------------------------
-- Table `ecoPlastic`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`usuario` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `genero` ENUM('Masculino', 'Femenino') NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `fecha_nacimiento` DATE NULL,
  `userImage` VARCHAR(255) NULL,
  `estadoUsuario` TINYINT(1) NOT NULL DEFAULT 1,
  `empresa_idempresa` INT NOT NULL,
  `roles_idroles` INT NOT NULL,
  PRIMARY KEY (`idusers`),
  INDEX `fk_usuario_empresa1_idx` (`empresa_idempresa` ASC) VISIBLE,
  INDEX `fk_usuario_roles1_idx` (`roles_idroles` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `ecoPlastic`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `ecoPlastic`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`usuario_auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`usuario_auth` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`usuario_auth` (
  `usuario_idusers` INT NOT NULL,
  `password` VARCHAR(255) NULL,
  `fecha_registro` DATETIME NOT NULL,
  `lastLogin` DATETIME NULL,
  `isTemporal` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`usuario_idusers`),
  CONSTRAINT `fk_usuario_auth_usuario1`
    FOREIGN KEY (`usuario_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`informacion_adicional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`informacion_adicional` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`informacion_adicional` (
  `empresa_idempresa` INT NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`empresa_idempresa`),
  CONSTRAINT `fk_informacion_adicional_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `ecoPlastic`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`configuracion_cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`configuracion_cuenta` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`configuracion_cuenta` (
  `usuario_idusers` INT NOT NULL,
  `estadoOnline` ENUM('Offline', 'Online') NOT NULL DEFAULT 'Offline',
  `temaApp` ENUM('Claro', 'Oscuro') NULL DEFAULT 'Claro',
  PRIMARY KEY (`usuario_idusers`),
  CONSTRAINT `fk_configuracion_cuenta_usuario1`
    FOREIGN KEY (`usuario_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`preguntas_seguridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`preguntas_seguridad` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`preguntas_seguridad` (
  `fk_idusers` INT NOT NULL,
  `pregunta_1` VARCHAR(255) NOT NULL,
  `pregunta_2` VARCHAR(255) NOT NULL,
  `respuesta_1` VARCHAR(255) NOT NULL,
  `respuesta_2` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`fk_idusers`),
  CONSTRAINT `fk_preguntas_seguridad_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`codigo_verificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`codigo_verificacion` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`codigo_verificacion` (
  `fk_idusers` INT NOT NULL,
  `codigo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`fk_idusers`),
  CONSTRAINT `fk_codigo_verificacion_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`contacto_emergencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`contacto_emergencia` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`contacto_emergencia` (
  `usuario_idusers` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `celular` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usuario_idusers`),
  CONSTRAINT `fk_contacto_emergencia_usuario1`
    FOREIGN KEY (`usuario_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`notas_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`notas_usuario` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`notas_usuario` (
  `fk_idusers` INT NOT NULL,
  `nota` TEXT NOT NULL,
  INDEX `fk_notas_usuario_usuario1_idx` (`fk_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_notas_usuario_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`informacion_ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`informacion_ubicacion` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`informacion_ubicacion` (
  `fk_idusers` INT NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  `localida` VARCHAR(255) NOT NULL,
  `barrio` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `adicionales` TEXT NULL,
  PRIMARY KEY (`fk_idusers`),
  CONSTRAINT `fk_informacion_ubicacion_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`archivos_adjuntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`archivos_adjuntos` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`archivos_adjuntos` (
  `idArchivo` INT NOT NULL AUTO_INCREMENT,
  `nombreServidor` VARCHAR(255) NOT NULL,
  `nombreCliente` VARCHAR(255) NOT NULL,
  `pesoArchivo` VARCHAR(45) NOT NULL,
  `extensionArchivo` VARCHAR(10) NOT NULL,
  `fechaCreado` DATETIME NOT NULL,
  PRIMARY KEY (`idArchivo`));


-- -----------------------------------------------------
-- Table `ecoPlastic`.`ref_archivos_adjuntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`ref_archivos_adjuntos` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`ref_archivos_adjuntos` (
  `fk_idArchivo` INT NOT NULL,
  `seccionReferencia` VARCHAR(255) NOT NULL,
  `idReferencia` VARCHAR(255) NOT NULL,
  INDEX `fk_ref_archivos_adjuntos_archivos_adjuntos1_idx` (`fk_idArchivo` ASC) VISIBLE,
  CONSTRAINT `fk_ref_archivos_adjuntos_archivos_adjuntos1`
    FOREIGN KEY (`fk_idArchivo`)
    REFERENCES `ecoPlastic`.`archivos_adjuntos` (`idArchivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
