-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 23:35:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecoPlastic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecoPlastic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecoPlastic` DEFAULT CHARACTER SET utf8 ;
USE `ecoPlastic` ;

-- -----------------------------------------------------
-- Table `ecoPlastic`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`empresa` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(100) NOT NULL,
  `nombre_empresa` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `imageUrl` VARCHAR(255) NULL,
  PRIMARY KEY (`idempresa`));


-- -----------------------------------------------------
-- Table `ecoPlastic`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`roles` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`roles` (
  `idroles` INT NOT NULL AUTO_INCREMENT,
  `name_rol` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idroles`));


-- -----------------------------------------------------
-- Table `ecoPlastic`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`usuario` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `genero` ENUM('Masculino', 'Femenino') NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(50) NULL,
  `fecha_nacimiento` DATE NULL,
  `userImage` VARCHAR(255) NULL,
  `estadoUsuario` TINYINT(1) NOT NULL DEFAULT 1,
  `empresa_idempresa` INT NOT NULL,
  `roles_idroles` INT NOT NULL,
  PRIMARY KEY (`idusers`),
  INDEX `fk_usuario_empresa1_idx` (`empresa_idempresa` ASC) VISIBLE,
  INDEX `fk_usuario_roles1_idx` (`roles_idroles` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `ecoPlastic`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `ecoPlastic`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`usuario_auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`usuario_auth` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`usuario_auth` (
  `usuario_idusers` INT NOT NULL,
  `password` VARCHAR(255) NULL,
  `fecha_registro` DATETIME NOT NULL,
  `lastLogin` DATETIME NULL,
  `isTemporal` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`usuario_idusers`),
  CONSTRAINT `fk_usuario_auth_usuario1`
    FOREIGN KEY (`usuario_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`informacion_adicional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`informacion_adicional` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`informacion_adicional` (
  `empresa_idempresa` INT NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`empresa_idempresa`),
  CONSTRAINT `fk_informacion_adicional_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `ecoPlastic`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`configuracion_cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`configuracion_cuenta` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`configuracion_cuenta` (
  `usuario_idusers` INT NOT NULL,
  `estadoOnline` ENUM('Offline', 'Online') NOT NULL DEFAULT 'Offline',
  `temaApp` ENUM('Claro', 'Oscuro') NULL DEFAULT 'Claro',
  PRIMARY KEY (`usuario_idusers`),
  CONSTRAINT `fk_configuracion_cuenta_usuario1`
    FOREIGN KEY (`usuario_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`preguntas_seguridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`preguntas_seguridad` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`preguntas_seguridad` (
  `fk_idusers` INT NOT NULL,
  `pregunta_1` VARCHAR(255) NOT NULL,
  `pregunta_2` VARCHAR(255) NOT NULL,
  `respuesta_1` VARCHAR(255) NOT NULL,
  `respuesta_2` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`fk_idusers`),
  CONSTRAINT `fk_preguntas_seguridad_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`codigo_verificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`codigo_verificacion` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`codigo_verificacion` (
  `fk_idusers` INT NOT NULL,
  `codigo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`fk_idusers`),
  CONSTRAINT `fk_codigo_verificacion_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`contacto_emergencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`contacto_emergencia` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`contacto_emergencia` (
  `usuario_idusers` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `celular` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usuario_idusers`),
  CONSTRAINT `fk_contacto_emergencia_usuario1`
    FOREIGN KEY (`usuario_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`notas_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`notas_usuario` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`notas_usuario` (
  `fk_idusers` INT NOT NULL,
  `nota` TEXT NOT NULL,
  INDEX `fk_notas_usuario_usuario1_idx` (`fk_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_notas_usuario_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`informacion_ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`informacion_ubicacion` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`informacion_ubicacion` (
  `fk_idusers` INT NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  `localida` VARCHAR(255) NOT NULL,
  `barrio` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `adicionales` TEXT NULL,
  PRIMARY KEY (`fk_idusers`),
  CONSTRAINT `fk_informacion_ubicacion_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`archivos_adjuntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`archivos_adjuntos` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`archivos_adjuntos` (
  `idArchivo` INT NOT NULL AUTO_INCREMENT,
  `nombreServidor` VARCHAR(255) NOT NULL,
  `nombreCliente` VARCHAR(255) NOT NULL,
  `pesoArchivo` VARCHAR(45) NOT NULL,
  `extensionArchivo` VARCHAR(10) NOT NULL,
  `fechaCreado` DATETIME NOT NULL,
  PRIMARY KEY (`idArchivo`));


-- -----------------------------------------------------
-- Table `ecoPlastic`.`ref_archivos_adjuntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`ref_archivos_adjuntos` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`ref_archivos_adjuntos` (
  `fk_idArchivo` INT NOT NULL,
  `seccionReferencia` VARCHAR(255) NOT NULL,
  `idReferencia` VARCHAR(255) NOT NULL,
  INDEX `fk_ref_archivos_adjuntos_archivos_adjuntos1_idx` (`fk_idArchivo` ASC) VISIBLE,
  CONSTRAINT `fk_ref_archivos_adjuntos_archivos_adjuntos1`
    FOREIGN KEY (`fk_idArchivo`)
    REFERENCES `ecoPlastic`.`archivos_adjuntos` (`idArchivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


DROP TABLE IF EXISTS `ecoPlastic`.`categoria` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`));


-- -----------------------------------------------------
-- Table `ecoPlastic`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`productos` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `categoria_idcategoria` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `createdate` DATETIME NULL,
  `comments` TINYINT(1) NOT NULL DEFAULT 1,
  `isocultar` TINYINT(1) NOT NULL DEFAULT 1,
  `usuario_idusers` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_categoria1_idx` (`categoria_idcategoria` ASC) ,
  INDEX `fk_productos_usuario1_idx` (`usuario_idusers` ASC) ,
  CONSTRAINT `fk_productos_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `ecoPlastic`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_usuario1`
    FOREIGN KEY (`usuario_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`rating` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`rating` (
  `idrating` INT NOT NULL,
  `calificacion` INT NOT NULL,
  `productos_idproductos` INT NOT NULL,
  PRIMARY KEY (`idrating`),
  INDEX `fk_rating_productos1_idx` (`productos_idproductos` ASC) VISIBLE,
  CONSTRAINT `fk_rating_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `ecoPlastic`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



DROP TABLE IF EXISTS `ecoPlastic`.`explorador_archivos_usuario` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`explorador_archivos_usuario` (
  `fk_idArchivo` INT NOT NULL,
  `fk_userID` INT NOT NULL,
  `rutaCompleta` TEXT NOT NULL,
  `favorito` TINYINT(1) NOT NULL,
  `isImage` TINYINT(1) NOT NULL DEFAULT 0,
  `esCompartido` TINYINT(1) NOT NULL DEFAULT 0,
  INDEX `fk_explorador_archivos_usuario_archivos_adjuntos1_idx` (`fk_idArchivo` ASC) ,
  INDEX `fk_explorador_archivos_usuario_usuario1_idx` (`fk_userID` ASC) ,
  CONSTRAINT `fk_explorador_archivos_usuario_archivos_adjuntos1`
    FOREIGN KEY (`fk_idArchivo`)
    REFERENCES `ecoPlastic`.`archivos_adjuntos` (`idArchivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_explorador_archivos_usuario_usuario1`
    FOREIGN KEY (`fk_userID`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


    DROP TABLE IF EXISTS `ecoPlastic`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `comentario` TEXT NOT NULL,
  `calificacion` INT NOT NULL DEFAULT 1,
  `fk_idproductos` INT NOT NULL,
  `fk_idusers` INT NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `fk_comentarios_productos1_idx` (`fk_idproductos` ASC) ,
  INDEX `fk_comentarios_usuario1_idx` (`fk_idusers` ASC) ,
  CONSTRAINT `fk_comentarios_productos1`
    FOREIGN KEY (`fk_idproductos`)
    REFERENCES `ecoPlastic`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_usuario1`
    FOREIGN KEY (`fk_idusers`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


    -- -----------------------------------------------------
-- Table `ecoPlastic`.`solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`solicitudes` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`solicitudes` (
  `idSolicitud` INT NOT NULL AUTO_INCREMENT,
  `mensaje` TEXT NOT NULL,
  `createDate` DATETIME NOT NULL,
  `fk_idproductos` INT NOT NULL,
  `idusers_envia` INT NOT NULL,
  `estado` ENUM('En revision', 'Aprobada', 'Rechazada') NOT NULL DEFAULT 'En revision',
  PRIMARY KEY (`idSolicitud`),
  INDEX `fk_solicitudes_productos1_idx` (`fk_idproductos` ASC),
  INDEX `fk_solicitudes_usuario1_idx` (`idusers_envia` ASC),
  CONSTRAINT `fk_solicitudes_productos1`
    FOREIGN KEY (`fk_idproductos`)
    REFERENCES `ecoPlastic`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_usuario1`
    FOREIGN KEY (`idusers_envia`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`producto_de_intercambio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`producto_de_intercambio` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`producto_de_intercambio` (
  `solicitudes_idSolicitud` INT NOT NULL,
  `productos_idproductos` INT NOT NULL,
  INDEX `fk_producto_de_intercambio_solicitudes1_idx` (`solicitudes_idSolicitud` ASC) ,
  INDEX `fk_producto_de_intercambio_productos1_idx` (`productos_idproductos` ASC) ,
  CONSTRAINT `fk_producto_de_intercambio_solicitudes1`
    FOREIGN KEY (`solicitudes_idSolicitud`)
    REFERENCES `ecoPlastic`.`solicitudes` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_de_intercambio_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `ecoPlastic`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`mensajes_solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`mensajes_solicitud` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`mensajes_solicitud` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `fk_idSolicitud` INT NOT NULL,
  `textoMensaje` TEXT NOT NULL,
  `fechaMensaje` DATETIME NOT NULL,
  `fk_idUsuarioEnvia` INT NOT NULL,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk_mensajes_solicitud_solicitudes1_idx` (`fk_idSolicitud` ASC) ,
  INDEX `fk_mensajes_solicitud_usuario1_idx` (`fk_idUsuarioEnvia` ASC) ,
  CONSTRAINT `fk_mensajes_solicitud_solicitudes1`
    FOREIGN KEY (`fk_idSolicitud`)
    REFERENCES `ecoPlastic`.`solicitudes` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_solicitud_usuario1`
    FOREIGN KEY (`fk_idUsuarioEnvia`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



DROP TABLE IF EXISTS `ecoPlastic`.`pedido` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`pedido` (
  `fk_idSolicitud` INT NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `departamento` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(255) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `nombreResponsable` VARCHAR(255) NOT NULL,
  `celularResponsable` VARCHAR(255) NOT NULL,
  INDEX `fk_pedido_solicitudes1_idx` (`fk_idSolicitud` ASC),
  PRIMARY KEY (`fk_idSolicitud`),
  CONSTRAINT `fk_pedido_solicitudes1`
    FOREIGN KEY (`fk_idSolicitud`)
    REFERENCES `ecoPlastic`.`solicitudes` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecoPlastic`.`notificaciones_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecoPlastic`.`notificaciones_usuario` ;

CREATE TABLE IF NOT EXISTS `ecoPlastic`.`notificaciones_usuario` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `fk_userID` INT NOT NULL,
  `referenciaLink` VARCHAR(255) NOT NULL,
  `estadoNotificacion` TINYINT(1) NOT NULL DEFAULT 0,
  `nombreNotificacionReferencia` VARCHAR(255) NOT NULL,
  `idReferencia` VARCHAR(255) NOT NULL,
  `nombreTipo` VARCHAR(255) NOT NULL,
  `fechaNotificacion` DATETIME NOT NULL,
  `fk_idSender` INT NOT NULL,
  PRIMARY KEY (`idNotificacion`),
  INDEX `fk_notificaciones_usuario_usuario1_idx` (`fk_userID` ASC) ,
  INDEX `fk_notificaciones_usuario_usuario2_idx` (`fk_idSender` ASC) ,
  CONSTRAINT `fk_notificaciones_usuario_usuario1`
    FOREIGN KEY (`fk_userID`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificaciones_usuario_usuario2`
    FOREIGN KEY (`fk_idSender`)
    REFERENCES `ecoPlastic`.`usuario` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
